dev:
    app_function: app.app
    aws_region : us-west-1
    manage_roles : true
    profile_name: null
    project_name: ubd-tool
    runtime: python3.7
    s3_bucket: ${{secrets.BUCKET}}
    vpc_config:
      SubnetIds: 
        ${{secrets.SUBNET1}}
        ${{secrets.SUBNET2}}
      SecurityGroupIds:
        ${{secrets.SECURITY_GROUP}}
    environment_variables:
      NEPTUNEDBRO:
        ${{secrets.NEPTUNEDBRO}}
