name: Testing

on:
  push:
    branches: 
      - main
    path:
      - zappa_settings.yml
  workflow_dispatch:

jobs:
  deploy:
    name: Zappa Deploy
    runs-on: ubuntu-latest

    environment:
      name: zappa

    steps:
    - uses: actions/checkout@main
    - name: Get Python3
      uses: actions/setup-python@v1
      with:
        python-version: 3.6 

    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    - name: Install Dependencies
      run: |
        pip3 install setuptools
        pip3 install -r requirements.txt

    - name: Run Zappa
      run: |
        python -m venv ./venv
        source venv/bin/activate
        'echo "$ZAPPA_SETTINGS" > zappa_settings.json'
        zappa update dev
      env:
        ZAPPA_SETTINGS = ${{secrets.ZAPPA_SETTINGS}}
