name: Testing

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  unittest:
    name: Neptune and S3 Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Get Python3
      uses: actions/setup-python@v1
      with:
        python-version: 3.6 

    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    - name: Install Dependencies
      run: |
        pip3 install setuptools
        pip3 install -r requirements.txt

    - name: Run S3 PyTest
      run: |
        cd tests
        pytest -v -s test_s3.py

    - name: Run Graph DB PyTest
      run: |
        export NEPTUNEDBRO=ws://localhost:8182/gremlin
        wget -q https://mirrors.sonic.net/apache/tinkerpop/3.4.10/apache-tinkerpop-gremlin-server-3.4.10-bin.zip
        unzip -q apache-tinkerpop-gremlin-server-3.4.10-bin.zip
        cd apache-tinkerpop-gremlin-server-3.4.10
        bin/gremlin-server.sh conf/gremlin-server-modern.yaml &
        cd ../tests
        pytest -v -s test_graphdb.py
        pkill gremlin
        pkill java
